emp_app/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
urlpatterns = [
    path('',views.index, name = 'index'),
    path('view_all_emp', views.all_emp, name='all_emp'),
    path('add_emp', views.add_emp, name='add_emp'),
    path('remove_emp', views.remove_emp, name='remove_emp'),
    path('remove_emp/<int:emp_id>/', views.remove_emp, name='remove_emp'),

    path('filter_emp', views.filter_emp, name='filter_emp'),

]

office_emp_proj/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('emp_app.urls'))
]

details/models.py
from django.db import models
from django.core.validators import RegexValidator
from datetime import datetime



# Create your models here.

class Personal_Information(models.Model):
    registration_num = models.CharField(max_length=10, unique=True, editable=False, verbose_name='Employee Id', null=True)

    def registration_number(self):
        current_year = datetime.now().year
        # Logic to generate registration number based on the year
        return f"{current_year}-{self.pk}"  # Example format: 2022-1, 2022-2, ...

    def save(self, *args, **kwargs):
        if not self.pk:  # Only generate registration number for new instances
            current_year = datetime.now().year
            last_registered = Personal_Information.objects.filter(registration_num__startswith=current_year).order_by(
                '-registration_num').first()
            if last_registered:
                last_number = int(last_registered.registration_num.split('-')[-1])
                self.registration_num = f"{current_year}-{last_number + 1}"
            else:
                self.registration_num = f"{current_year}-1"
        super().save(*args, **kwargs)

    full_name = models.CharField(max_length=100)
    cnic_regex = RegexValidator(
        regex=r'^\d{5}-\d{7}-\d{1}$',  # CNIC format: 00000-0000000-0
        message="CNIC must be in the format: '00000-0000000-0'",
    )
    cnic_image = models.ImageField(null=True)
    cnic = models.CharField(max_length=15, validators=[cnic_regex],help_text=('format: xxxxx-xxxxxxx-x'))
    MALE = 'M'
    FEMALE = 'F'
    OTHER = 'O'

    GENDER_CHOICE = [
        (MALE, 'Male'),
        (FEMALE, 'Female'),
        (OTHER, 'Other'),
    ]
    gender = models.CharField(max_length=1, choices=GENDER_CHOICE)
    date_of_birth = models.DateField()
    present_address = models.CharField(max_length=100)
    permanent_address = models.CharField(max_length=100)
    contact_number = models.CharField(max_length=15)
                                      # validators=[RegexValidator(
            # regex=r'^\d{12}$',
            # message='Enter a 12-digit number.',
            # code='invalid_twelve_digit_number'
        # )]

    alternate_contact = models.CharField(max_length=15)
    # validators=[RegexValidator(
    #         regex=r'^\d{11}$',
    #         message='Enter a 12-digit number.',
    #         code='invalid_twelve_digit_number'
    #     )]
    # )
    email = models.EmailField()

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = "Personal Information"
        verbose_name_plural = "Personal Informations"  # Optional, for plural form

class Educational_Background(models.Model):
    personal_info = models.ForeignKey(Personal_Information, on_delete=models.CASCADE)
    degree = models.CharField(max_length=100, verbose_name='Title of Degree/Certificate/Sanad')
    degree_image = models.ImageField(verbose_name='Image of Any Degree/Certificate/Sanad',null=True)
    institue = models.CharField(max_length=100, verbose_name='Institute/Hoza/Madrasa')
    GRADE_CHOICE = [
        ('A+', 'A+'),
        ('A', 'A'),
        ('B+', 'B+'),
        ('B', 'B'),
        ('C', 'C'),
        ('D', 'D'),
        ('E', 'E'),
        ('F', 'F'),

    ]
    grade = models.CharField(max_length=2, choices=GRADE_CHOICE)

    passing_year = models.DateField(null=True)

    class Meta:
        verbose_name = "Educational Background"
        verbose_name_plural = "Educational Background"  # Optional, for plural form


class otherProfessionalSkill(models.Model):
    personal_info = models.ForeignKey(Personal_Information, on_delete=models.CASCADE)

    position = models.CharField(max_length=100)
    company = models.CharField(max_length=100, verbose_name='Organization/company/Employer Name')
    certificte = models.ImageField(verbose_name='Related Image',null=True)
    _from = models.CharField(max_length=100, verbose_name='From')
    to = models.CharField(max_length=100, verbose_name='To')

    class Meta:
        verbose_name = "Other Professional Skill"
        verbose_name_plural = "Other Professional Skills"  # Optional, for plural form


class professionalSkills(models.Model):
    personal_info = models.ForeignKey(Personal_Information, on_delete=models.CASCADE)

    description = models.CharField(max_length=1000, verbose_name='Description')

    class Meta:
        verbose_name = 'PROFESSIONAL SKILL'
        verbose_name_plural = 'PROFESSIONAL SKILLS'


class relgiousOrPolicts(models.Model):
    personal_info = models.ForeignKey(Personal_Information, on_delete=models.CASCADE)

    position = models.CharField(max_length=100)
    name = models.CharField(max_length=100, verbose_name='Name of party or association')
    assosiation = models.ImageField(verbose_name='Related Image',null=True)

    _from = models.CharField(max_length=100, verbose_name='From')
    to = models.CharField(max_length=100, verbose_name='To')

    class Meta:
        verbose_name = 'RELIGIOUS OR Political Affiliation'
        verbose_name_plural = 'RELIGIOUS OR Political Affiliations'


class refrence(models.Model):
    personal_info = models.ForeignKey(Personal_Information, on_delete=models.CASCADE)

    name = models.CharField(max_length=100)
    relation = models.CharField(max_length=100, verbose_name='Relation with applicant')
    contact_number = models.CharField(max_length=12, validators=[
        RegexValidator(
            regex=r'^\+?1?\d{9,15}$',  # Validates international phone numbers
            message="Phone number must be entered in the format: '+999999999'. Up to 12 digits allowed."
        )
    ])

    class Meta:
        verbose_name = 'Reference'
        verbose_name_plural = 'References'


class Documents(models.Model):
    personal_info = models.ForeignKey(Personal_Information, on_delete=models.CASCADE)

    photo = models.ImageField(verbose_name='Passport Size Photographs')
    documents = models.ImageField(verbose_name='Copy of all educational documents')
    document = models.ImageField(verbose_name='Only Education Documents(If you need then use this otherwise skip this)',null=True)
    documen = models.ImageField(verbose_name='Only Education Documents(If you need then use this otherwise skip this)',null=True)


    teaching = models.ImageField(verbose_name='Teaching Experience letter (if applicable)', null=True)
    skills = models.ImageField( verbose_name='Skill certificates (if any)')


class Resignation(models.Model):
    personal_info = models.ForeignKey(Personal_Information, on_delete=models.CASCADE)

    personal_inf = models.OneToOneField(Personal_Information, on_delete=models.CASCADE,related_name='my')

    YES = 'yes'
    NO = 'no'

    APPROVED = [
        (YES, 'yes'),
        (NO, 'no'),
    ]
    Approval = models.CharField(max_length=3, choices=APPROVED,null=True)
    experience_letter = models.CharField(max_length=3,choices=APPROVED,null=True)

    resignation_image = models.ImageField(null=True)
    resignation_date = models.DateField(verbose_name='Resignation Date')
    reason = models.TextField(verbose_name='Reason for Resignation')

    class Meta:
        verbose_name = 'Only Use When you want to resign from office'
        verbose_name_plural = 'Only Use When you want to resign from office'

emp_app/models.py
from django.db import models
from reporting_officers.models import *

# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=100, null=False)
    location = models.CharField(max_length=100)


    def __str__(self):
        return self.name

class Role(models.Model):
    name = models.CharField(max_length=100, null=False)


    def __str__(self):
        return self.name


class Employee(models.Model):

    first_name = models.CharField(max_length=100, null=False)
    last_name = models.CharField(max_length=100, null=False)
    SYED = 'Syed'
    MIRZA = 'Mirza'
    NONSYED = 'Non-Syed'

    CASTE_CHOICE = [
        (SYED, 'Syed'),
        (MIRZA, 'Mirza'),
        (NONSYED, 'Non Syed'),
    ]
    Title = models.CharField(max_length=10,choices=CASTE_CHOICE,default=NONSYED)
    dept = models.ForeignKey(Department, on_delete=models.CASCADE, related_name='employees', null=True)
    salary = models.IntegerField(default=0, verbose_name='Salary Cap')
    bonus = models.IntegerField(default=0, verbose_name='Basic Salary')
    allowance = models.IntegerField(default=0, verbose_name='Total Daily Allowance', null=True)  # Corrected field name
    officers = models.ForeignKey(Data, on_delete=models.CASCADE, verbose_name='Reporting Officer', null=True)  # Updated field
    FLEXIBLE = 'Flexible'
    FOUR = '4'
    EIGHT = '8'
    WORK_HOURS = [
        (FLEXIBLE,'Flexible'),
        (FOUR, '4'),
        (EIGHT, '8'),
    ]
    allowed_working_hours = models.CharField(max_length=8,null=True,choices=WORK_HOURS)
    role = models.ForeignKey(Role, on_delete=models.CASCADE, related_name='employees')

    phone = models.CharField(max_length=12, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

templates/add_emp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add employee</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
 <body>
  <div class="container">
    <h1>Add An Employee</h1>

      <hr>
  <form action="/add_emp" method="post">
      {% csrf_token %}
        <label for="first_name">First Name</label><br>
        <input type="text" id="first_name" name="first_name" value="{{ first_name }}"><br>


          <label for="last_name">Last Name</label><br>
    <input type="text" id="last_name" name="last_name" value="{{ last_name }}"><br>


        <label for="dep">Department</label><br>
    <input type="text" id="Department" name="dept" value="{{ dept }}"><br>      

          <label for="salary">Salary</label><br>
    <input type="number" id="Salary" name="salary" value="{{ salary }}"><br>


          <label for="bonus">Bonus</label><br>
    <input type="number" id="bonus" name="bonus" value="{{ bonus }}"><br>
  

      <label for="role">Role</label><br>
    <input type="text" id="role" name="role" value="{{ role }}"><br>


          <label for="number">Phone Number</label><br>
    <input type="number" id="phone" name="phone" value="{{ phone }}"><br>
      
   <label for="number">Location</label><br>
    <input type="text" id="location" name="location" value="{{ Department.locations }}"><br>    



    


      
 

    <hr>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/change_form.html
{% extends 'admin/change_form.html' %}{# due to csrf issue #}
{% csrf_token %}

{% load static %}

{% block admin_change_form_document_ready %}
    {{ block.super }}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"
            type="application/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>

  <script>
        // Wait for the document to be fully loaded
        document.addEventListener('DOMContentLoaded', function() {
            // Apply input mask for phone number
            $('#id_cnic').mask('00000-0000000-0');

            {#// Apply input mask for date#}
            {#$('#date').mask('99/99/9999');#}

            $('#id_phone').mask ('(00) 0000000000')
            var my = document.getElementById("id_phone");
            my.placeholder = "(00) 000-0000000";
        
            
              $('#id_contact_number').mask ('(00) 0000000000')
            var input = document.getElementById("id_contact_number");
            input.placeholder = "(00) 000-0000000";
            
            $('#id_alternate_contact').mask ('(00) 0000000000')
            var input2 = document.getElementById("id_alternate_contact");
            input2.placeholder = "(00) 000-0000000";


            var input3 = document.getElementById("id_email");
            input3.placeholder = "abcd@abc.com";

             var input4 = document.getElementById("id_present_address");
            input4.placeholder = "123 Main Street Anytown, USA12345";

            var input5 = document.getElementById("id_permanent_address");
            input5.placeholder = "123 Main Street Anytown, USA12345";

            var input6 = document.getElementById("id_date_of_birth");
            input6.placeholder = "2024-04-02";

            var input7 = document.getElementById("id_cnic");
            input7.placeholder = "12345-6789012-3";
            
            var input8 = document.getElementById("id_full_name");
            input8.placeholder = "Alice Johnson";
            
            {#var input9 = document.getElementById("id_clock_in_1");#}
            {#inpute9.#}

            
            
        });
    </script>
{% endblock %}

templates/filter_emp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employ Filters</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
 <body>
  <div class="container">
    <h1>Filter Employee</h1>
        <form action="/filter_emp" method="post">
      {% csrf_token %}
        <label for="name">First/Last Name</label><br>
        <input type="text" id="name" name="name" value="{{ name }}"><br>





        <label for="dep">Department</label><br>
    <input type="text" id="Department" name="dept" value="{{ dept }}"><br>





      <label for="role">Role</label><br>
    <input type="text" id="role" name="role" value="{{ role }}"><br>











    <hr>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
      <hr>
      

</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    <title>Office Management</title>
  </head>
  <body>
  <div class="container">
    <h1>Office Management System</h1>

      <input id="cnic" type="text">

      <hr>
      
      <a class="btn btn-primary" href="view_all_emp" role="button">All Employee</a>
      <a class="btn btn-primary" href="add_emp" role="button">Add An Employee</a>
      <a class="btn btn-primary" href="remove_emp" role="button">Remove An Employee</a>
      <a class="btn btn-primary" href="filter_emp" role="button">Filter Employee Details</a>

</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
 

  </body>
</html>

templates/remove_emp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Remove Employ</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <h1>Remove An Employee</h1>
    <hr>
    <!-- Example single danger button -->
    <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            Choose Emplyee to remove
        </button>
        <ul class="dropdown-menu">
            {% for emp in emps %}
            <li><a class="dropdown-item" href="/remove_emp/{{ emp.id }}">{{ emp.first_name }} {{ emp.last_name }}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/view_all_emp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>all employee</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
 <body>
  <div class="container">
    <h1>All Employee Details</h1>

      <hr>

     <table class="table table-bordered">
  <thead>
    <tr style="background-color: #8d8787">
      <th scope="col">Id</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">dept</th>
      <th scope="col">salary</th>
      <th scope="col">bonus</th>
      <th scope="col">role</th>
      <th scope="col">phone</th>
      <th scope="col">location</th>
    </tr>
  </thead>
         {% for emp in emps %}
  <tbody>
    <tr>
      <th scope="row">{{ emp.id }}</th>
      <td>{{ emp.first_name }}</td>
      <td>{{ emp.last_name }}</td>
      <td>{{ emp.dept }}</td>
        <td>{{ emp.salary }}</td>
        <td>{{ emp.bonus }}</td>
        <td>{{ emp.role }}</td>
        <td>{{ emp.phone }}</td>
        <td>{{ emp.dept.location }}</td>


    </tr>
  </tbody>
         {% endfor %}
</table>

</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>